export const ACTION_SIGN_IN = "ACTION_SIGN_IN";
export const ACTION_SIGN_IN_SUCCESS = "ACTION_SIGN_IN_SUCCESS";
export const ACTION_SIGN_IN_FAILED = "ACTION_SIGN_IN_FAILED";
export const ACTION_UPDATE_SIGN_IN_UI_STATE = "ACTION_UPDATE_SIGN_IN_UI_STATE";

export const ACTION_SIGN_UP = "ACTION_SIGN_UP";
export const ACTION_SIGN_UP_SUCCESS = "ACTION_SIGN_UP_SUCCESS";
export const ACTION_SIGN_UP_FAILED = "ACTION_SIGN_UP_FAILED";
export const ACTION_UPDATE_SIGN_UP_UI_STATE = "ACTION_UPDATE_SIGN_UP_UI_STATE";

export const ACTION_CONFIRM_SIGN_UP = "ACTION_CONFIRM_SIGN_UP";
export const ACTION_CONFIRM_SIGN_UP_SUCCESS = "ACTION_CONFIRM_SIGN_UP_SUCCESS";
export const ACTION_CONFIRM_SIGN_UP_FAILED = "ACTION_CONFIRM_SIGN_UP_FAILED";
export const ACTION_UPDATE_CONFIRM_SIGN_UP_UI_STATE =
  "ACTION_UPDATE_CONFIRM_SIGN_UP_UI_STATE";

export const ACTION_ADD_ORGANIZATION = "ACTION_ADD_ORGANIZATION";
export const ACTION_ADD_ORGANIZATION_SUCCESS =
  "ACTION_ADD_ORGANIZATION_SUCCESS";
export const ACTION_ADD_ORGANIZATION_FAILED = "ACTION_ADD_ORGANIZATION_FAILED";

export const ACTION_GET_NOTIFICATIONS = "ACTION_GET_NOTIFICATIONS";
export const ACTION_GET_NOTIFICATIONS_SUCCESS =
  "ACTION_GET_NOTIFICATIONS_SUCCESS";
export const ACTION_GET_NOTIFICATIONS_FAILED =
  "ACTION_GET_NOTIFICATIONS_FAILED";
export const ACTION_UPDATE_GET_NOTIFICATIONS_UI_STATE =
  "ACTION_UPDATE_GET_NOTIFICATIONS_UI_STATE";
export const UPDATE_STOP_NOTIFICATIONS_CALLBACK_STATE =
  "UPDATE_STOP_NOTIFICATIONS_CALLBACK_STATE";
export const ACTION_UPDATE_NOTIFICATIONS_PAGINATION_STATE =
  "ACTION_UPDATE_NOTIFICATIONS_PAGINATION_STATE";

export const ACTION_GET_NOTIFICATIONS_BACKGROUND =
  "ACTION_GET_NOTIFICATIONS_BACKGROUND";

export const ACTION_ADD_USER = "ACTION_ADD_USER";
export const ACTION_ADD_USER_SUCCESS = "ACTION_ADD_USER_SUCCESS";
export const ACTION_RESET_ADD_USER_SUCCESS_STATE =
  "ACTION_RESET_ADD_USER_SUCCESS_STATE";
export const ACTION_ADD_USER_FAILED = "ACTION_ADD_USER_FAILED";
export const ACTION_UPDATE_ADD_USER_UI_STATE =
  "ACTION_UPDATE_ADD_USER_UI_STATE";

export const ACTION_GET_USERS = "ACTION_GET_USERS";
export const ACTION_GET_USERS_SUCCESS = "ACTION_GET_USERS_SUCCESS";
export const ACTION_GET_USERS_FAILED = "ACTION_GET_USERS_FAILED";
export const ACTION_UPDATE_GET_USERS_UI_STATE =
  "ACTION_UPDATE_GET_USERS_UI_STATE";
export const ACTION_UPDATE_USERS_PAGINATION_STATE =
  "ACTION_UPDATE_USERS_PAGINATION_STATE";

export const ACTION_GET_ORGANIZATION = "ACTION_GET_ORGANIZATION";
export const ACTION_GET_ORGANIZATION_SUCCESS =
  "ACTION_GET_ORGANIZATION_SUCCESS";
export const ACTION_GET_ORGANIZATION_FAILED = "ACTION_GET_ORGANIZATION_FAILED";
export const ACTION_UPDATE_GET_ORGANIZATION_UI_STATE =
  "ACTION_UPDATE_GET_ORGANIZATION_UI_STATE";

export const ACTION_UPDATE_ADD_ORGANIZATION_UI_STATE =
  "ACTION_UPDATE_ADD_ORGANIZATION_UI_STATE";

export const ACTION_NEW_REQUEST = "ACTION_NEW_REQUEST";
export const ACTION_NEW_REQUEST_SUCCESS = "ACTION_NEW_REQUEST_SUCCESS";
export const ACTION_NEW_REQUEST_FAILED = "ACTION_NEW_REQUEST_FAILED";
export const ACTION_UPDATE_NEW_REQUEST_UI_STATE =
  "ACTION_UPDATE_NEW_REQUEST_UI_STATE";

export const ACTION_UPDATE_USER_PROFILE = "ACTION_UPDATE_USER_PROFILE";
export const ACTION_UPDATE_USER_PROFILE_SUCCESS =
  "ACTION_UPDATE_USER_PROFILE_SUCCESS";
export const ACTION_UPDATE_USER_PROFILE_FAILED =
  "ACTION_UPDATE_USER_PROFILE_FAILED";
export const ACTION_UPDATE_USER_PROFILE_UI_STATE =
  "ACTION_UPDATE_USER_PROFILE_UI_STATE";

export const ACTION_GET_REQUESTS = "ACTION_GET_REQUESTS";
export const ACTION_GET_REQUESTS_SUCCESS = "ACTION_GET_REQUESTS_SUCCESS";
export const ACTION_GET_REQUESTS_FAILED = "ACTION_GET_REQUESTS_FAILED";
export const ACTION_UPDATE_GET_REQUESTS_UI_STATE =
  "ACTION_UPDATE_GET_REQUESTS_UI_STATE";

export const ACTION_UPDATE_ORGANIZATION_INFO =
  "ACTION_UPDATE_ORGANIZATION_INFO";
export const ACTION_UPDATE_ORGANIZATION_INFO_SUCCESS =
  "ACTION_UPDATE_ORGANIZATION_INFO_SUCCESS";
export const ACTION_UPDATE_ORGANIZATION_INFO_FAILED =
  "ACTION_UPDATE_ORGANIZATION_INFO_FAILED";
export const ACTION_UPDATE_ORGANIZATION_INFO_UI_STATE =
  "ACTION_UPDATE_ORGANIZATION_INFO_UI_STATE";

export const UPDATE_STOP_CALLBACK_HELL_STATE =
  "UPDATE_STOP_CALLBACK_HELL_STATE";

export const ACTION_UPDATE_PAUSE_USERS_INFINITE_CALLBACK_STATE =
  "ACTION_UPDATE_PAUSE_USERS_INFINITE_CALLBACK_STATE";

export const ACTION_UPDATE_REQUESTS_STATE = "ACTION_UPDATE_REQUESTS_STATE";

export const ACTION_ACCEPT_REQUEST = "ACTION_ACCEPT_REQUEST";
export const ACTION_ACCEPT_REQUEST_SUCCESS = "ACTION_ACCEPT_REQUEST_SUCCESS";
export const ACTION_ACCEPT_REQUEST_FAILED = "ACTION_ACCEPT_REQUEST_FAILED";
export const ACTION_UPDATE_ACCEPT_REQUEST_UI_STATE =
  "ACTION_UPDATE_ACCEPT_REQUEST_UI_STATE";
export const ACTION_UPDATE_REQUEST_PAGINATION_STATE =
  "ACTION_UPDATE_REQUEST_PAGINATION_STATE";
export const ACTION_DELETE_REQUEST_LOCAL = "ACTION_DELETE_REQUEST_LOCAL";
export const ACTION_RESET_REQUEST_SUCCESS_STATE =
  "ACTION_RESET_REQUEST_SUCCESS_STATE";

export const ACTION_REJECT_REQUEST = "ACTION_REJECT_REQUEST";
export const ACTION_REJECT_REQUEST_SUCCESS = "ACTION_REJECT_REQUEST_SUCCESS";
export const ACTION_REJECT_REQUEST_FAILED = "ACTION_REJECT_REQUEST_FAILED";
export const ACTION_UPDATE_REJECT_REQUEST_UI_STATE =
  "ACTION_UPDATE_REJECT_REQUEST_UI_STATE";

export const ACTION_GET_PROFILE = "ACTION_GET_PROFILE";
export const ACTION_GET_PROFILE_SUCCESS = "ACTION_GET_PROFILE_SUCCESS";
export const ACTION_GET_PROFILE_FAILED = "ACTION_GET_PROFILE_FAILED";
export const ACTION_UPDATE_GET_PROFILE_UI_STATE =
  "ACTION_UPDATE_GET_PROFILE_UI_STATE";

export const SIGNOUT = "SIGNOUT";

export const REACT_APP_API_URL = "http://localhost:3050";
export const REACT_APP_PUBLIC_VAPID_KEY =
  "BJra13F_F_0FnBXhbL9ATZX9oA9S81WY0pR31ntr9qMrurWmVyFQzOso8M4pFfdE4-9Go68KUb7C3yZPkm8dBmk";

export const ACTION_RESET_REQUESTS_REDUCER_STATE =
  "ACTION_RESET_REQUESTS_REDUCER_STATE";

export const ACTION_RESET_USERS_REDUCER_STATE =
  "ACTION_RESET_USERS_REDUCER_STATE";

export const ACTION_RESET_UPDATE_PROFILE_STATE =
  "ACTION_RESET_UPDATE_PROFILE_STATE";

export const ACTION_RESET_UPDATE_ORGANIZATION_STATE =
  "ACTION_RESET_UPDATE_ORGANIZATION_STATE";

export const ACTION_GET_REQUESTS_STATUS_WIDGET_DATA =
  "ACTION_GET_REQUESTS_STATUS_WIDGET_DATA";
export const ACTION_GET_REQUESTS_STATUS_WIDGET_DATA_SUCCESS =
  "ACTION_GET_REQUESTS_STATUS_WIDGET_DATA_SUCCESS";
export const ACTION_GET_REQUESTS_STATUS_WIDGET_DATA_FAILED =
  "ACTION_GET_REQUESTS_STATUS_WIDGET_DATA_FAILED";
export const ACTION_UPDATE_GET_REQUESTS_STATUS_WIDGET_DATA_UI_STATE =
  "ACTION_UPDATE_GET_REQUESTS_STATUS_WIDGET_DATA_UI_STATE";

export const ACTION_GET_REQUESTS_COUNTS_WIDGET_DATA =
  "ACTION_GET_REQUESTS_COUNTS_WIDGET_DATA";
export const ACTION_GET_REQUESTS_COUNTS_WIDGET_DATA_SUCCESS =
  "ACTION_GET_REQUESTS_COUNTS_WIDGET_DATA_SUCCESS";
export const ACTION_GET_REQUESTS_COUNTS_WIDGET_DATA_FAILED =
  "ACTION_GET_REQUESTS_COUNTS_WIDGET_DATA_FAILED";
export const ACTION_UPDATE_GET_REQUESTS_COUNTS_WIDGET_DATA_UI_STATE =
  "ACTION_UPDATE_GET_REQUESTS_COUNTS_WIDGET_DATA_UI_STATE";


  export const ACTION_UPDATE_SESSION_STATUS =
  "ACTION_UPDATE_SESSION_STATUS";